### ISSUE TITLE
How to convert a fairseq checkpoint to a huggingface checkpoint

### ISSUE THREAD

**Issue by z592694590** [yizhilll/MERT#14]
Hi, thanks for this great job.
I have trained a mert model by your repo. But I can't use the fairseq checkpoint to infer. Could you provide some help？I see the demo of infer is based on huggingface. How can I convert a fairseq checkpoint to a huggingface checkpoint.

**Comment by yizhilll** [comment]
Hi, I've uploaded scripts for conversion. Please check with the scripts:
```
bash scripts/convert_HF_script.sh default mert config_mert_base [/absolute/path/to/a/fairseq/checkpoint.pt]
```
