### ISSUE TITLE
Will the tokens be released in the future?

### ISSUE THREAD

**Issue by A-Quarter-Mile** [yizhilll/MERT#3]
Hello MERT maintainers,

I'm interested in the k-means tokens mentioned in your project. I would like to know if you have any plans to release these tokens in the future. If so, could you provide an estimated timeline for the release?

Thank you for your great work on this project, and I'm looking forward to your response.

Best regards,
Yuning

**Comment by yizhilll** [comment]
Hi, thanks for asking. 

The K-means tokens are currently not available for publication. We'll review about the availability of the tokens:)
