### ISSUE TITLE
finetuned model for downstream tasks?

### ISSUE THREAD

**Issue by jidanhuang** [yizhilll/MERT#7]
hello, is it possible to open the checkpoint of model for downstream tasks?

**Comment by yizhilll** [comment]
@jidanhuang Thanks for being interested in our project. 

We do not have a version of MERT "fine-tuned" on downstream tasks. 

However, we do have [a demo based on 95M model for multiple downstream tasks](https://huggingface.co/spaces/m-a-p/Music-Descriptor). The MLP layers and codes  for loading the checkpoints are available in the [corresponding repo](https://huggingface.co/spaces/m-a-p/Music-Descriptor/tree/main).

We'll release more downstream checkpoints.
